version: '3.4'

services:
  app:
    # image: gocrypt
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile
    ports:
      - 8080:8080
    
    # depends_on:
    #   - mysql
  
  # mysql:
  #   build
    
